## 1. Robust Calculator (types & conversions, error handling)
Write a calculator program that accepts two operands and an operator (+, -, *, /). Accept numbers as integers or floats (or numeric strings), convert types safely, and handle division-by-zero and invalid input with clear error messages. Add a mode that reads expressions like '12.5 * 3' and evaluates them after validating tokens.

In [95]:
# Create a function to accept three arguements
def calculator():
    ''' This function accepts two operands and an operator (+, -, *, /), and performs the
    arithmetic operation specified by the operator on the operands. You have an option to select 1-line mode
    which allows you to type the whole expression at once, or 3-line mode for entering one value at a time.'''

    try:
        # choosing between a mode that takes the individual values of the expression, one at a time, or all values at once
        mode = int(input('Choose mode. Type 1 for 1-line mode, and 3 for 3-line mode'))
        if mode == 1:
            value = input('Type the expression you want to evaluate, E.g. 1 + 2. Ensure to add a space between them i.e 1 + 2, not 1+2: ')
            value = value.split()

            # handling a situation where a user enters the expression without spacing the values and entering less than 3 values
            try:
                first_num = float(value[0])
                operator = value[1]
                second_num = float(value[2])
            except ValueError:
                return 'Please enter valid numbers and ensure there is a space between the digits. E.g. 1 + 2'
            except IndexError:
                return 'Please enter three values. Two operands (a number or a decimal) and one operator (+, -, *, /). \
                Ensure to add a space between them'

            # Doing calulations for the 1-line mode and handling errors
            try:
                if len(value) != 3:
                    return 'Please enter three values. Two operands (a number or a decimal) and one operator (+, -, *, /)'
                if operator == '+':
                    answer = first_num + second_num
                    return answer
                elif operator == '-':
                    answer = first_num - second_num
                    return answer
                elif operator == '/':
                    answer = first_num / second_num
                    return answer
                elif operator == '*':
                    answer = first_num * second_num
                    return answer
                elif operator not in ['+', '-', '*', '/']:
                    return 'You entered an invalid operator. Please use one of the following: +, -, *, /'
            except ZeroDivisionError:
                return 'You can not divide by 0. Please enter a valid denominator'
            except ValueError:
                return 'You can only perform operations on whole numbers and decimals. Please enter a valid operand'
            # Doing calulations for the 3-line mode and handling errors
        elif mode == 3:
            try:
                first_num = float(input('Enter the first number: '))
                operator = input('Enter the operation you want to perform: ')
                second_num = float(input('Enter the second number: '))
                if operator == '+':
                    answer = first_num + second_num
                    return answer
                elif operator == '-':
                    answer = first_num - second_num
                    return answer
                elif operator == '/':
                    answer = first_num / second_num
                    return answer
                elif operator == '*':
                    answer = first_num * second_num
                    return answer
                elif operator not in ['+', '-', '*', '/']:
                    return "You entered an invalid operator. Please use one of the following: +, -, *, /"
            except ZeroDivisionError:
                return 'You can not divide by 0. Please enter a valid denominator'
            except ValueError:
                return 'You can only perform operations on whole numbers and decimals. Please enter a valid operand'
        
        else:
            return 'Please choose an available mode ( 1 or 3)'
    except ValueError:
        return 'You can only enter a whole number or a decimal. Please enter a valid mode'

In [96]:
help(calculator)

Help on function calculator in module __main__:

calculator()
    This function accepts two operands and an operator (+, -, *, /), and performs the
    arithmetic operation specified by the operator on the operands. You have an option to select 1-line mode
    which allows you to type the whole expression at once, or 3-line mode for entering one value at a time.

## 2. Student Records — CRUD with Lists & Dicts
Implement a student record manager that stores records as dictionaries inside a list. Support add, view (by id), update, delete, and list all. Validate fields (age numeric, GPA 0.0–4.0).

In [185]:
# create students record as dictionaries inside a list
records = [{'id' : 1, 'name' : 'Gba Peter', 'age' : 25, 'GPA' : 3.95}, {'id' : 2, 'name' : 'Mark Jameson', 'GPA' : 2.7, 'age' : 27}]

In [213]:
# create a function to add a record
def add_record():
    ''' This function gets the name and GPA of a student from an input and add them to the students' records database. \
    The student's id is automatically generated using the size of the existing records. '''
    # get student's details from inputs and size of the existing records list
    id = len(records) + 1
    ids = []
    for i in records:
        ids.append(i['id'])
    ''' ensure the new id created does not already exist in the records. This is necessary because, when some records get deleted,
    the id generated using len(records) will likely return a duplicate id'''
    if id in ids:    
        id = max(ids) + 1
        
    name = input("Enter student's name: ")
    try:
        GPA = float(input("Enter student's GPA: "))
        age = int(input("Enter student's age in years: "))
    except ValueError:
        return 'GPA and age can only be decimal or whole number (for age)'

    if GPA >= 0.0 and GPA <= 4.0:
        # create a dictionary of the student's details entered
        rec_dict = {'id' : id, 'name' : name, 'GPA' : GPA, 'age' : age}
    
        # add the dictionary to the records list
        records.append(rec_dict)
        return "The student's record has been added"
    else:
        return 'GPA can not be less than 0 or greater than 4'

In [188]:
# view a student's record by id
def view_record():
    ''' This function takes a student's id from an input and returns their record '''
    
    # Get the student id and ensure its a whole number
    try:    
        id = int(input("Enter student's id: "))
    except ValueError:
        return 'ID must be a number'
    
    # create a list of existing ids
    ids = []
    for i in records:
        ids.append(i['id'])
    # view only existing records
    if id in ids:    
        return records[id - 1]
    elif id not in ids:
        return "Student's record not found"

In [201]:
# update a student's record
def update_record():
    ''' This function takes a student's id from an input and updates their specified details '''
    
    # Get the student id and ensure its a whole number
    try:    
        id = int(input("Enter student's id: "))
    except ValueError:
        return 'ID must be a number'
    
    # create a list of existing ids
    ids = []
    for i in records:
        ids.append(i['id'])
        
    # update only existing records
    if id in ids:
        to_change = input('What do you want to change? enter 1 for name, 2 for GPA, and 3 for age')
        if to_change == '1':
            name = input("Enter new name: ")
            records[id - 1]['name'] = name
            return "Student's name successfully updated"
        elif to_change == '2':
            try:
                GPA = float(input("Enter new GPA: "))
            except ValueError:
                return 'GPA can only be a decimal or a whole number'
    
            if GPA >= 0.0 and GPA <= 4.0:
                records[id - 1]['GPA'] = GPA
                return "Student's GPA successfully updated"
            else:
                return 'GPA can not be less than 0 or greater than 4'
        elif to_change == '3':
            try:
                age = int(input("Enter new age: "))
                records[id - 1]['age'] = age
                return "Student's age successfully updated"
            except ValueError:
                return 'Age can only be a whole number'
        else:
            return 'Please enter 1 to change name, 2 to change GPA, or 3 to change age. No other value is allowed'
        
    elif id not in ids:
        return "Student's record not found"

In [190]:
# delete a student's record
def delete_record():
    ''' This function takes a student's id from an input and deletes their details  from the records database'''
    
    # Get the student id and ensure its a whole number
    try:    
        id = int(input("Enter student's id: "))
    except ValueError:
        return 'ID must be a number'
    
    # create a list of existing ids
    ids = []
    for i in records:
        ids.append(i['id'])
        
    # delete only existing records
    if id in ids:
        del(records[id - 1])
        return "Student's record successfully deleted"
    elif id not in ids:
        return "Student's record not found"

In [175]:
# list all students' records
import pandas as pd
def list_records(record):
    df_record = pd.DataFrame(record)
    return df_record

In [217]:
#delete_record()
add_record()

Enter student's name:  Ken Bity
Enter student's GPA:  1.76
Enter student's age in years:  23

"The student's record has been added"

In [218]:
list_records(records)

   id              name  age   GPA
0   1         Gba Peter   25  3.95
1   2      Mark Jameson   27  2.70
2   3  Happiness Adikpe   23  2.86
3   5        Yange Kate   22  2.50
4   6          Andy Ter   31  2.65
5   7          Ken Bity   23  1.76

## 3. Nested Grading Logic (control flow & aggregation)
Given students assessment scores, compute weighted totals and assign letter grades with +/- tiers using nested conditionals. Produce class summary statistics (mean, median, grade distribution) and write a short text report.

In [252]:
# define students' scores in various subjects and create a function to find their weighted totals
peter = [97, 95, 98]
andy = [25, 60, 74]
mike = [58, 59, 40]

students = [peter, mike, andy]

def weighted_total(score):
    total = 0.3 * score[0] + 0.2 * score[1] + 0.5 * score[2]
    return total

In [253]:
# create a list containg all students' weighted total
class_totals = [weighted_total(i) for i in students]
class_totals

[97.1, 49.2, 56.5]

In [255]:
# assign grades based on scores

score = weighted_total(peter)
if score > 100:
    print('Incorrect entry, score can not exceed 100')
elif score >= 97:
    print('A+')
elif score >= 93:
    print('A')
elif score >= 90:
    print('A-')
elif score >= 87:
    print('B+')
elif score >= 83:
    print('B')
elif score >= 80:
    print('B-')
elif score >= 77:
    print('C+')
elif score >= 73:
    print('C-')
elif score >= 70:
    print('C')
elif score >= 67:
    print('D+')
elif score >= 63:
    print('D-')
elif score >= 60:
    print('D')
else:
    print('F')

A+

In [257]:
# compute class mean
class_avg = round(sum(class_totals)/len(class_totals),1)
class_avg

67.6

In [306]:
# compute class median
sorted_scores = sorted(class_totals)
if len(sorted_scores) % 2 == 0:
    mid_nums = [sorted_scores[round(len(sorted_scores)/2) - 1], sorted_scores[round(len(sorted_scores)/2)]]
    class_median = round(sum(mid_nums)/len(mid_nums), 1)
else:
    class_median = sorted_scores[round(len(sorted_scores)/2) - 1]
    
class_median

56.5

In [307]:
# short report
print(f'In a class of {len(students)} students, the average score for this semester is {class_avg} and the median score is {class_median}.')

In a class of 3 students, the average score for this semester is 67.6 and the median score is 56.5.

## 4. Contact Search & Deduplication (strings & comprehensions)
Build a contact loader into a list of dicts, implement case-insensitive substring search (name/phone/email), and deduplicate contacts by phone or email. Output cleaned CSV and a brief log of removed duplicates.

In [309]:
import pandas as pd
# list of dictionaries containing contact details
contacts = [{'name' : 'Peter', 'phone' : '09020025453', 'email' : 'gba03@mail.com'},
            {'name' : 'Peter', 'phone' : '09020025453', 'email' : 'gba03@mail.com'},
            {'name' : 'Andrew', 'phone' : '09020025693', 'email' : 'andy@mail.com'},
            {'name' : 'Kane', 'phone' : '08027625453', 'email' : 'kane@mail.com'},
            {'name' : 'Kane', 'phone' : '08027625453', 'email' : 'kane@mail.com'},
            {'name' : 'Jane', 'phone' : '08128900453', 'email' : 'jane@mail.com'}]
df_contacts = pd.DataFrame(contacts)
df_contacts.to_csv('contacts.csv', index = False)

In [311]:
df = pd.read_csv('contacts.csv', index_col = 0)
df

             phone           email
name
Peter   9020025453  gba03@mail.com
Peter   9020025453  gba03@mail.com
Andrew  9020025693   andy@mail.com
Kane    8027625453   kane@mail.com
Kane    8027625453   kane@mail.com
Jane    8128900453   jane@mail.com

In [315]:
import csv

def load_and_clean_contacts(input_file, output_file):
    contacts = []
    seen_emails = set()
    seen_phones = set()
    removed_log = []

    with open(input_file, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            email = row['email'].strip().lower()
            phone = row['phone'].strip()

            # Check for duplicates
            if email in seen_emails or phone in seen_phones:
                removed_log.append(row)
                continue
            
            # If unique, add to our list and mark as seen
            seen_emails.add(email)
            seen_phones.add(phone)
            contacts.append(row)

    # Output Cleaned CSV
    if contacts:
        keys = contacts[0].keys()
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(contacts)

    # Output Log
    print( 'Process Completed!')
    print(f"Cleaned contacts saved to: {output_file}")
    print(f"Duplicates removed: {len(removed_log)}")
    for item in removed_log:
        print(f"  > Removed: {item['name']} (Duplicate Email/Phone)")
    
    return contacts

In [316]:
cleaned_data = load_and_clean_contacts('contacts.csv', 'cleaned_contacts.csv')

Process Complete!
Cleaned contacts saved to: cleaned_contacts.csv
Duplicates removed: 2
  > Removed: Peter (Duplicate Email/Phone)
  > Removed: Kane (Duplicate Email/Phone)

In [317]:
def search_contacts(contacts, query):
    query = query.lower()
    results = []

    for c in contacts:
        # Check if query exists in any of the three fields
        if (query in c['name'].lower() or 
            query in c['phone'].lower() or 
            query in c['email'].lower()):
            results.append(c)
    
    return results

In [324]:
search_contacts(contacts, '90')

[{'name': 'Peter', 'phone': '09020025453', 'email': 'gba03@mail.com'},
 {'name': 'Peter', 'phone': '09020025453', 'email': 'gba03@mail.com'},
 {'name': 'Andrew', 'phone': '09020025693', 'email': 'andy@mail.com'},
 {'name': 'Jane', 'phone': '08128900453', 'email': 'jane@mail.com'}]

## 5. Loop Practice — Prime Gap Finder (loops)
Write script to find all pairs of consecutive primes ≤ 10,000 with gaps ≥ 20 and save them

In [388]:
# Creating a list with prime numbers <=10000

primes = []
factors = []
for i in range(2, 10001):
    # skip all even numbers and numbers divisible by 5 for efficiency
    if i > 2 and i % 2 == 0:
        continue
    elif i > 5 and i % 5 == 0:
        continue
    for j in range(i):
        # skip 0 to avoid zero division error
        if j == 0:
            continue
        # check if a number is divisible by numbers below it and add them to a list of factors
        elif i % j == 0:
            factors.append(j)
    # if a number has only one factor (itself), add it to a list of prime numbers
    if len(factors) == 1:
        primes.append(i)
    factors = []

In [389]:
# creating a list containing primes with gaps >= 20

primes_with_gap20 = []

for i in range(len(primes)):
    # handle index out of range error while subtracting numbers from the ones after them to check gaps
    try:
        if primes[i + 1] - primes[i] >= 20:
            primes_with_gap20.append(primes[i])
    except IndexError:
        pass

In [390]:
primes_with_gap20

[887,
 1129,
 1327,
 1637,
 1669,
 1951,
 2179,
 2311,
 2477,
 2557,
 2971,
 3089,
 3137,
 3229,
 3271,
 3413,
 3469,
 3739,
 3947,
 3967,
 4027,
 4177,
 4297,
 4523,
 4759,
 4831,
 5119,
 5237,
 5351,
 5449,
 5531,
 5591,
 5717,
 5749,
 5903,
 5953,
 5987,
 6173,
 6397,
 6427,
 6491,
 6737,
 6803,
 6917,
 7079,
 7129,
 7253,
 7369,
 7649,
 7759,
 7793,
 7963,
 8017,
 8123,
 8243,
 8329,
 8389,
 8467,
 8543,
 8783,
 8867,
 8893,
 8971,
 9067,
 9257,
 9349,
 9439,
 9551,
 9697]

## 6. BMI Logger with Unit Options (I/O, validation, datetime)
Create a BMI logger that accepts entries in metric or imperial units, validates input, converts units, computes BMI category, and appends timestamped records to CSV. Provide a function to display the last 10 entries and simple ASCII trend bars.

In [467]:
# import relevant modules
import csv
import os
from datetime import datetime as dt

# create a list of records to add to csv
records =  []


# create function for logger

def logger():

    # create a list of records to add to csv
    records =  []

    # get weight and height from users and ensure they are in the right format
    try:    
        weight = float(input('Enter weight in grams: '))
        height = float(input('Enter height in centimeters: '))
    except ValueError:
        return 'Weight and height can only be a whole number or a decimal'

    # convert units to kilograms and meters
    weight_in_kg = weight/1000
    height_in_m = height/100
    timestamp = dt.now().strftime('%Y-%m-%d %H:%M:%S')
    bmi_category = ''

        
    bmi = weight_in_kg/(height_in_m ** 2)

    # assign bmi categories
    if bmi >= 30:
        bmi_category = 'Obesity'
    elif bmi >= 25:
        bmi_category = 'Overweight'
    elif bmi >= 18.5:
        bmi_category = 'Healthy weight'
    else:
        bmi_category = 'Underweight'

    # create a list of records to add to csv
    records =  [weight_in_kg, height_in_m, bmi, bmi_category, timestamp]

    #check if file exists
    file_exists = os.path.exists('bmi_records.csv')

    # Open file in append mode ("a") or create if it does not exist
    with open('bmi_records.csv', mode='a', newline='') as file:
        writer = csv.writer(file)
    
        # If file doesn't exist, create headers
        if not file_exists:
            writer.writerow(['weight_in_kg', 'height_in_m', 'bmi', 'bmi_category', 'timestamp'])
    
        # Add the record
        writer.writerow(records)

        # display result to show that action was successful
    return 'New record successfully added!!!'

In [492]:
logger()

Enter weight in grams:  50000
Enter height in centimeters:  128

'New record successfully added!!!'

In [482]:
import pandas as pd

# create function to display last 10 entries
def display_entries(file = 'bmi_records.csv'):
    '''This function returns the last 10 rows of a CSV file as a pandas DataFrame.
    If file has less than 10 rows, it returns all rows'''
    df = pd.read_csv(file)
    last_10 = df.tail(10)
    return last_10

In [493]:
display_entries()

   weight_in_kg  height_in_m        bmi    bmi_category            timestamp
0          68.0         1.72  22.985398  Healthy weight  2025-12-28 15:04:43
1          62.0         1.68  21.967120  Healthy weight  2025-12-28 15:05:01
2          40.0         1.54  16.866251     Underweight  2025-12-28 15:05:16
3          25.0         1.00  25.000000      Overweight  2025-12-28 15:05:38
4          50.0         1.28  30.517578         Obesity  2025-12-28 15:06:01

In [497]:
# function to display simple ASCII trend bars for bmi

def ascii_bars(last_10 = display_entries()):
    # loop through the bmi column and plot bars
    for i in last_10['bmi']:
        print('#' * int(i))

In [498]:
ascii_bars()

######################
#####################
################
#########################
##############################

## 7. Adaptive Guessing Game (loops, state persistence)
Implement a number guessing game where difficulty range adjusts based on player streaks. Track attempts per round and persist top-5 high scores

In [432]:
# import module to generate random numbers
import random

# create list to track the scores
scores = []
num_attempts = []
streak = 0
upper_bound = 10

# create loop for game
while True:
    
    guess = ''
    attempts = 0
    score = 0
    
    
    while True:
        # generate random number
        num = random.randint(1, upper_bound)

        # handle error if the user press enter without typing anything, or entering an alphabet or a character
        try:
            guess = int(input(f'Guess a number between 1 and {upper_bound}: '))
        except ValueError:
            print('Please enter a number')
        attempts +=1
    
        if attempts == 5 and guess != num:
            print('You attempted 5 times without getting it right. Game over!!!')
            num_attempts.append(attempts)
            scores.append(score)
            break
        elif guess != num:
            upper_bound = 10
            print('Wrong, guess again')
            
        # track streaks and adjust difficulty range
        elif num == guess and attempts == 1:
            streak +=1
            upper_bound = 10 * (streak + 1)
            num_attempts.append(attempts)
            score += 100
            attempts = 0
        elif num == guess and attempts != 1:
            num_attempts.append(attempts)
            score += (5 - attempts) * 20
            attempts = 0
            upper_bound = 10
        
    
    play_again = input('Type y to play again, or n to quit game: ')
    if play_again.lower() == 'n':
        top5_scores = sorted(scores, reverse = True)[:5]
        break

Guess a number between 1 and 10:  3

Wrong, guess again

Guess a number between 1 and 10:  2

Wrong, guess again

Guess a number between 1 and 10:  5

Wrong, guess again

Guess a number between 1 and 10:  6

Wrong, guess again

Guess a number between 1 and 10:  5

You attempted 5 times without getting it right. Game over!!!

Type y to play again, or n to quit game:  y
Guess a number between 1 and 10:  7
Guess a number between 1 and 20:  7

Wrong, guess again

Guess a number between 1 and 10:  8

Wrong, guess again

Guess a number between 1 and 10:  9

Wrong, guess again

Guess a number between 1 and 10:  3

Wrong, guess again

Guess a number between 1 and 10:  2

You attempted 5 times without getting it right. Game over!!!

Type y to play again, or n to quit game:  y
Guess a number between 1 and 10:  4

Wrong, guess again

Guess a number between 1 and 10:  3

Wrong, guess again

Guess a number between 1 and 10:  6

Wrong, guess again

Guess a number between 1 and 10:  7

Wrong, guess again

Guess a number between 1 and 10:  8

You attempted 5 times without getting it right. Game over!!!

Type y to play again, or n to quit game:  n

In [434]:
# store top5 scores in a file (persistence)
# Open file in write mode
with open('top5_scores.txt', 'w') as file:
   for score in top5_scores:
       file.write(f'{score}\n')